# Generated by Django 3.1.8 on 2021-07-26 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupFieldTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_field', models.CharField(max_length=64)),
            ],
            options={
                'lookup_fields': 'name',
            },
        ),
        migrations.CreateModel(
            name='MultipleLookupFieldsTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_field1', models.CharField(max_length=64)),
                ('lookup_field2', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group1', models.CharField(max_length=10)),
                ('group2', models.CharField(max_length=10)),
                ('with_empty', models.CharField(blank=True, max_length=10, null=True)),
                ('integer', models.IntegerField(blank=True, null=True)),
                ('float', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('boolean', models.BooleanField(default=False)),
                (
                    'multiple_field_lookup',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='multiplelookupfieldstestmodel',
                    )
                ),
                (
                    'simple_lookup',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='lookupfieldtestmodel',
                    )
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    )
                ),
            ],
        ),
    ]
